### ISSUE TITLE
Re-Assign Diagnostic.py emails to Atiq and Ernie

### ISSUE THREAD

**Issue by DanielJWood** [energyapps/egallon-serve#4]
Hi Chauncey, 

We need the emails that result from the eGallon and utilities jenkins jobs to be sent to Ernie and Atiq instead of myself. There should be a total of four emails sent each week to each of them. Their titles are: 

* Egallon Disgnostic Report 
* Egallon Processor Report
* Utility Processor Report
* Utility Disgnostic Report

**NOTE** we should correct "Disgnostic" to "Diagnostic" in the subject line of that automated email.

**Comment by chaunceyt** [comment]
PR https://github.com/energygov/api_controllers/pull/1 merged.
